export const ProductsData = [
  {
    id: 1,
    name: "Indian Institute of Technology, Hyderabad",
    Rating: "4.0",
    Nirf: "NIRF\nRanked 8 out of 300",
    info: "IIT Hyderabad is an autonomous public technical university located in the Sangareddy District of Telangana. Established in 2008, IIT Hyderabad is a 2nd generation IIT and is ranked 8th in the engineering category by NIRF 2023. IIT Hyderabad campus is spread over a sprawling 600 acres and is home to 252 faculty members and 3903 students. IIT Hyderabad has a total of 17 departments for higher education.IIT Hyderabad offers BTech as its flagship program where admission JEE Advanced score based. IIT Hyderabad's previous year's cutoff for admission to the BTech course was 585 for CSE specialisation. The fee for the BTech course at IIT Hyderabad is INR 8.88 Lakhs (approximately). Return on investment has been particularly positive for IIT Hyderabad. The course's overall cost is INR 10.2 Lakhs, while the top package was INR 63.78 LPA. The average package was at INR 20.07 LPA. Check: IIT Hyderabad Admission IIT Hyderabad has been ranked on 3rd place for NIRF Innovation Ranking 2023. IIT hyderabad has partnered up with TATA Motors to develop software defined vehicles in a recent MoU. Moreover, the IIT Hyderabad and Greenko’ s BUILD program aims to support undergradaute students. Under this program, innovative ideas are given shape to build a startup. Students will also be provided financial aid of INR 1 Lakh, mentorship, prototyping support and co-working space. As per the latest new, IIT Hyderabad is now home to 130 startups with a revenue of INR 1200 Crore. ",
    adm: "IIT Hyderabad admission to its 30+ UG and PG courses is based on scores obtained in various national-level entrance exams. Aspiring candidates who aim to get into IIT Hyderabad flagship course B.Tech need to get clear the JEE Advanced exam followed by counseling conducted by JOSAA. JOSAA administers the seat allocation for IIT Hyderabad and holds 6 rounds where it allots seats based on parameters like JEE Advanced rank, availability of seats, category, etc. Candidates must register online for JoSAA counseling to participate in the seat allotment process. IIT Hyderabad B.Tech CSE is one of the most sought-after programs and candidates aiming to get admission there can expect the cut-off to range between 613 - 1586. Check IIT Hyderabad Cutoff At the PG level, IIT Hyderabad admissions are offered in M.Tech, M.Sc, M.Des, and Ph.D. programs. The institute shortlists eligible candidates for M.Tech admission based on the GATE score, followed by a PI round. For admission to the IIT Hyderabad M.Sc program, candidates are required to pass the IIT JAM test. Applicants seeking admission for IIT Hyderabad M.Des are selected on the basis of their merit score in CEED exams. Admission to the MA program requires an interview and a test administered by IIT Hyderabad. The institute also offers a doctoral program in different specializations for which it shortlists the eligible candidates based on CSIR-NET-JRF / UGC-NET-JRF score followed by an interview round. IIT Hyderabad has also started a certificate program in Future Wireless Communication this year.",
    fee: "Fee:B.Tech	₹2.23 Lakhs",
    plac: "IIT Hyderabad Placements 2023 is concluded with 74.90% placements. 570 students were placed with 621 offers. IIT Hyderabad highest package stood at INR 63.78 LPA whereas IIT Hyderabad average package stood at INR 20.07 LPA. 335 recruiters participated in the placement drive. Some of the top recruiters of IIT Hyderabad include Google, Microsoft, Amazon, Goldman Sachs, Flipkart, TSMC, Adobe etc.",
  },
  {
    id: 2,
    name: "International Institute of Information Technology (IIIT), Hyderabad",
    Rating: "4.0",
    Nirf: "NIRF\nRanked 54 out of 300",
    info: "IIIT Hyderabad is the first private deemed university founded through a non-profit public-private partnership (N-PPP). In the NIRF 2023 rankings for the engineering category, the institute is ranked 55. IIIT Hyderabad is well-known for its well-known for its Btech program.IIIT Hyderabad offers undergraduate, graduate, dual degree, and doctoral programmes in engineering, science, and information technology. Candidates must score lower than 1000 on the JEE Main exam in order to be admitted to the BTech programme. The BTech programme at IIIT Hyderabad has 140 available seats. Of those, 120 seats are set aside for applicants who take the JEE Main exam, and 20 seats are set up for applicants who use the SPEC method.MTech, MS, PhD, and dual degree programmes are provided by IIIT Hyderabad. Exams administered by the institutions themselves determine who gets into these programmes. The institute administers the UGEE for Dual Degree Admissions and the PGEE for MTech, MS, and PhD Admissions. Students can also apply for lateral entry admissions at IIIT Hyderabad by taking the LEEE test.",
    adm: "IIIT Hyderabad admission 2023 is ongoing. The institute grants admission to its various UG, PG, and Research programs on the basis of scores obtained in the entrance examination. Admission to IIIT Hyderabad flagship program BTech is offered through JEE Main or UGEE entrance scores IIIT Hyderabad conducts Postgraduate Entrance Exams (IIITH PGEE) to offer admission to various PG and Research courses such as M.Tech, M.S., Ph.D.. Application process for the same usually commences in the month of February, and the exam is conducted in the month of April every year. Eligible candidates can fill the IIIT Hyderabad application form for admission by visiting the official website - iiit.ac.in",
    fee: " Fee:B.Tech	₹3.6 Lakhs",
    plac: "IIIT Hyderabad has recently concluded its 2022 placement drive. A total of 400 students were eligible for the placement drive among which 392 of these students were placed. The highest salary increased by 32% as compared to the previous year & stood at INR 74 LPA this year. B.Tech CSE students received an average salary of INR 32 LPA. Students were recruited in Core Engineering industries, Software / IT Industries, Banks, Consultancy Firms, SaaS, R&D laboratories, and Academic Institutes.Some of the recruiters at IIIT Hyderabad included Bloomberg, Code Nation, Deloitte, Facebook, Google, HSBC, Indeed, Intuit, Jio, Nvidia, Qualcomm, Samsung, Swiggy, TCS, Uber, Walmart, Unacademy, Persistent, etc.",
  },
  {
    id: 3,
    name: "JNTUH College of Engineering (JNTUH CE), Hyderabad",
    Rating: "3.7",
    Nirf: "NIRF\nRanked 57 out of 200",
    info: "Jawaharlal Nehru Technological University, Hyderabad, was founded in 1972 as India's first Technological University. JNTUH is located in Kukatpally, Hyderabad, on a vast 89-acre campus. Currently, it has four constituent engineering colleges located in Hyderabad, Kondagattu (Jagithyal), Manthani, and Sultanpur (Medak Dist. ), as well as fifteen additional constituent units on the Hyderabad campus. JNTUH provides undergraduate B.Tech. programmes in 24 disciplines and B.Pharm. programmes; a five-year integrated dual degree masters programme; M.Tech. programmes in 68 disciplines; M.Pharm. programmes in 11 disciplines; M.Sc. programmes in 10 disciplines; and postgraduate MCA, MBA, and double degree programmes.The Jawaharlal Nehru Technological University is ranked 76 for B.Tech by NIRF 2022. It is ranked 80 for Overall by Outlook 2019. Furthermore, it was ranked 6 for Overall by ARIIA 2020, while the university was ranked 77 for B.Tech by Collegedunia 2023. It has also been accredited by NAAC with a Grade 'A' and approved by AICTE & UGC. According to the NIRF Rankings report of 2021, JNTUH has been ranked 62nd in the Engineering field. According to the NIRF Rankings report of 2021, JNTUH has been ranked 62nd in the Engineering field.",
    adm: "JNTUH offers its flagship program B.Tech for a duration of four years in 24 different specializations. Admission to the B.Tech program is strictly done on the basis of the merits secured by the candidates in the TS-EAMCET entrance exam followed by TS-EAMCET counseling for the final seat allotments. JNTUH charges a fee of INR 1.19 Lakhs per year for its B.Tech program.JNTUH admission process also involves other national and state-level examinations such as GATE, TS-ICET for the program such as M.Tech and MBA respectively. The selection criteria, cutoff, dates, eligibility, and application process are discussed in the article.",
    fee: "Fee:Btech 50000",
    plac: "The university takes admission by conducting entrance tests TS EAMCET, TS ECET, JEE Main, JEE Advanced, and GATE. It offers admission for undergraduate, graduate, and doctoral degrees such as B.Tech, B.Pharma, MBA, MCA, M.Tech, MS, and Ph.D, in multiple specializations. A number of global corporations have visited the campus of Jawaharlal Nehru Technological University to take part in recent placement drives, and the institution has a strong track record of placement. A few of the prominent firms, like Amazon and Microsoft, took part in the 2021 placement sessions, and Microsoft provided the institution with the highest wage package of INR 41 LPA.",
  },
  {
    id: 4,
    name: "University College of Engineering (UCE), Hyderabad",
    Rating: "4.7",
    Nirf: "NIRF\nRanked 88 out of 200",
    info: "University College of Engineering (UCE), Osmania University Hyderabad is a prestigious engineering institute founded in 1929. It is ranked at 88 for B.Tech by NIRF ranking 2020 and also holds a reputed status among many other ranking agencies. The institute offers B.E. at the UG level, M.Tech (Full-time/Part-time), MCA at the PG level. Admissions to all the courses will be based on the candidate’s performance in different entrance tests followed by centralized counselling.",
    adm: "Admissions to all the programmes will be based on the performance in the entrance test followed by centralized counselling. For admission to the PG courses, Osmania University conducts Osmania University Common Entrance Tests (OUCET) in order to evaluate candidates.Candidates who secure a minimum of 36% marks in the Entrance Test under General and Backward Class category and 15% marks under the Scheduled Caste/Scheduled Tribe Category will be considered for admission. In case of a tie at the entrance test, date of birth will be considered and the older candidate will be considered for admission first.",
    fee: "Fee:Bachelor of Engineering [BE] ₹ 35,000",
    plac: "University College of Engineering Osmania University has an active and dedicated Placements cell within it. It tends to inculcate skills and expertise while the candidates in the study. Some of the Top companies/concerns which the graduated candidates have placed are TRANSCO, Accenture, JP Morgan, ORACLE, Infosys, Amazon, Dee Shaw, Wipro, TCS, ITC, Maruti Suzuki, DURA, Cognizant, Tata motors and many more",
  },
  {
    id: 5,
    name: "National Institute of Technology Warangal",
    Rating: "4.3",
    info: "NIT Warangal is ranked 21 in the engineering category by NIRF 2023. NIT Warangal is an autonomous university, established in 1959. NIT Warangal provides 8 undergraduate and 29 postgraduate programmes across five disciplines. NIT Warangal provides PhD programmes in management, engineering, humanities, sciences, and physical education. The NIT Warangal campus size is 248 Acres.NIT Warangal offers BTech as its main program, available in 8 specializaions. The BTech fees for 1st year is INR 2.07 Lakh. Applicants must get a JEE Main exam rank between 450 and 17,000 in order to be considered for admission to the flagship programme. The JEE Main cutoff rank is used to determine admission to the programme, which is followed by the counselling process. ",
    adm: "NIT Warangal admission to more than 40 courses is based upon different national level exams as per courses accepted by the institute.B.Tech is the flagship course of NIT Warangal. The program is offered in 8 specializations. Admissions to NIT Warangal for the same are done on the basis of JEE Main scores followed by JoSAA Counseling. Candidates seeking admission to the flagship program must score a rank between 450-17,000. The total fee for the 4 year BTech program is INR 5.19 Lacs.",
    fee: "Fee:Tuition fee	62,500",
    plac: "NIT Warangal has an active placement cell named Centre for Career Planning & Development (CCPD) that conducts placement drives every year. Students receive lucrative salary packages during the placement drive. NIT Waranagal is conducting its placement drive for the batch 2023 and 1400 Job offers have been made. The highest Package offered was INR 88 LPA whereas the Average Package & Median Package stood at INR 17.29 LPA and INR 12.6 LPA respectively.",
  },
  {
    id: 6,
    name: "Birla Institute of Technology & Science (BITS), Hyderabad",
    Rating: "4.5",
    info: "BITS Pilani Hyderabad is a campus of BITS Pilani Goa University, established in 2008. BITS Pilani Hyderabad is UGC approved and accredited by NAAC with grade A. BITS Pilani Hyderabad is located in Hyderabad and the campus spans 200 acres. BITS Pilani Hyderabad is one of the four campuses of BITS. BITS Pilani offers undergraduate, postgraduate and doctoral courses. Moreover, regardless of BITSAT scores, BITS Pilani would offer first-rank holders from all central and state boards immediate admission to the curriculum of their choice.",
    adm: "BITS Pilani Hyderabad offers is BE Hons as its flagship course. Admission to the course is done via the BITSAT entrance test conducted by the BITS Pilani. The overall cutoff for the BE course of BITSAT was 203 - 372 marks for the general category in 2022. Apart from this, BITS Pilani Hyderabad also accept direct admission of state board toppers to its BE and BPharma courses.",
    fee: "Fee:BE {Hons.}	₹5.72 Lakhs",
    plac: "BITS Pilani Hyderabad Placements 2023 report has been released. The median pay package of BITS Pilani Campuses increased by 32.6%, from INR 22.62 LPA to INR 30 LPA. Furthermore, the average pay at the BITS Pilani campuses increased from INR 23 LPA to INR 30.37 LPA. The PPOs' final CTC increased from INR 45 LPA to INR 60.75 LPA. BITS Pilani Hyderabad's top recruiters are Aditya Birla Group, Adobe, Amazon, Cognizant, Bravo Lucy, CA Technologies, S & P Capital IQ, Cisco, Dell, and others.",
  },
  {
    id: 7,
    name: "Chaitanya Bharathi Institute of Technology, Hyderabad",
    Rating: "4.3",
    Nirf: "NIRF\nRanked 101-150 out of 200",
    info: "Chaitanya Bharathi Institute of Technology (CIBT), Hyderabad is a prestigious institute established in the year 1979. It is affiliated to Osmania University and has been approved by AICTE. The institute holds reputable status among many popular ranking agencies. It offers B.E/B.Tech at the UG level and ME, M.Tech, MBA, MCA at the PG level. The institute has maintained a positive placement rate in the four decades of its successful journey",
    adm: "At the UG level, the institute offers a B.E. in 7 specializations and a B.Tech. in four specializations for a duration of 4 years. Admission in B. Tech is done on the basis of marks scored in Engineering Agricultural and Medical Common Entrance Test",
    fee: "Fee:B.Tech	₹1.87 Lakhs",
    plac: "Chaitanya Bharathi Institute of technology has a dedicated Training and Placement Centre for students, established in 1987. In the year 2019-20, 1228 students were placed, out of which 1103 were from undergraduate programs and 125 were from PG programs.The institute has witnessed an increase in the no. of placement offers year after year. From the year 2000 onwards, a total number of 15284 students have been placed in leading companies",
  },
  {
    id: 8,
    name: "CVR College of Engineering, Hyderabad",
    Rating: "4.0",
    Nirf: "NIRF\nRanked 155 out of 300",
    info: "CVR College of Engineering was founded in 2001. It is situated in the state of Telangana. Degree courses are available at the institute, with 11 UG and 8 PG options. These programs are available in full-time mode. CVR College of Engineering is well-known for its M.E./M.Tech and B.E./B.Tech programs. These programs are taught by highly qualified professors. Candidates can pursue a variety of courses, including M.E./M.Tech and B.E./B.Tech in the Engineering stream. ",
    adm: "CVC College of Engineering offers admissions in 8 specializations in B.Tech and 6 specializations in M.Tech. Admissions are entrance based and offers are made to only those students to meet the cut-off.Admissions to B.Tech program requires students to either qualify TS EAMCET/JEE Main along with 45% aggregate in higher secondary school with PCM.",
    fee: "Fee:Bachelor of Technology [B.Tech] ₹ 115,000",
    plac: "Year after year, the college sets new marks. Despite the fact that it is a recession year, with over 100 firms visiting CVR and over 1500 placements for the 2022-23 academic year, it is the most among peer colleges. The average wage has risen dramatically to a new high. The biggest offer is a whopping Rs. 57,50,000, while several pupils received offers in excess of Rs. 25 lakhs. More than 100 students received offers for more than Rs. 10 lakhs, setting a new high. Around 300 bids exceed Rs. 6 lakhs.",
  },
  {
    id: 9,
    name: "MVSR Engineering College - MVSREC, Hyderabad",
    Rating: "3.9",
    Nirf: "NIRF\nRanked out of 200",
    info: "Maturi Venkata Subba Rao Engineering College is a private college in Hyderabad, Telangana that has been providing top-notch technical education since 1981. The college is sponsored by the Matrusri Education Society and recognized by AICTE. It is affiliated with Osmania University, Hyderabad, and has been accredited by NAAC with a ‘B++” grade and a score of 2.8. The college is one of the most sought after colleges in the state and every year more than 1000 students take admission in various courses offered by the college. ",
    adm: "Candidates seeking admission in B.E and B.Tech programmes need to appear in, Engineering Agricultural and Medical Common Entrance Test, commonly called as AP EAMCET, is an entrance examination required for admission to some engineering and medical colleges in the states of Andhra Pradesh. To get admission in Lateral entry candidates need to go through AP ECET, a national level entrance test.",
    fee: "Fee:BE	₹1.32 Lakhs",
    plac: "Many placement opportunities were provided in our college. Around 75% of students got placed recently with salary packages ranging between 4 LPA to 40 LPA. Top recruiting companies were Accenture, Amazon, and Wipro. The roles offered were design engineer and developer.",
  },
  {
    id: 10,
    name: "Vasavi College Of Engineering (VCE)",
    Rating: "4.1",
    info: "Vasavi College of Engineering (VCE) is an autonomous self-financed institute established in 1981. It is affiliated to Osmania University and is accredited by the NBA. According to NIRF Ranking 2020, the institute is ranked at 187th out of 300 in India and 12th in Hyderabad for B.Tech. It offers B.E.at the UG level and ME, M.Tech, MCA at the PG level. Reputed companies offer high salary packages to the students of this institute in the placement drive.",
    adm: "BE Admission: 70% of the seats of B.E. are allotted based on the candidate’s rank on TS-EAMCET. The remaining 30% of seats are fulfilled by the management quota. Admission to B.E. (Lateral) is based on candidate’s scores on TS-ECET",
    fee: "Fee:Bachelor of Engineering [BE] ₹ 130,000",
    plac: "Vasavi College of Engineering witnessed ups and downs during placements. The Institute has placed 441 students and the percentage of placements is 77.10%.The highest CTC of INR 21 LPA was offered this year. Highest stipend during the Internship upto 60 K was offered too.The highest CTC was offered by Service Now & Amazon.Top recruiting companies like Cognizant, TCS, LTI Limited, Accenture, Infosys and many more offered placements and internships. ",
  },
  {
    id: 11,
    name: "Sri Indu College of Engineering and Technology, Hyderabad",
    Rating: "4.5",
    Nirf: "outlook\nRanked 50 out of 100",
    info: "Sri Indu College of Engineering and Technology, Hyderabad established in 2001, is affiliated to JNTUH, Hyderabad and approved by AICTE. The college offers UG and PG courses in the discipline of Engineering & Technology and Management across various specializations, approved by UGC.",
    adm: "Sri Indu College of Engineering and Technology provides B.Tech, M.Tech, and MBA courses in their curriculum. Following are the details for the same.",
    fee: "Fee:Bachelor of Technology [B.Tech] ₹ 93,000",
    plac: "Students are eligible in the third year. There are so many companies visiting our college. The top companies are Microsoft, hcl,tcs, Infosys, etc. The highest package is 25 lakhs per annum. The average package is 4 lakhs per annum. 80 % of students are getting placed.",
  },
  {
    id: 12,
    name: "MLR Institute of Technology, Hyderabad",
    Rating: "3.8",
    Nirf: "NIRF\nRanked 151-200 out of 200",
    info: "MLR Institute of Technology is one of the best educational institutions that has been ranked 201-250 by NIRF Ranking for the year 2021. The institute offers 11 specializations in B.Tech, 4 in M.Tech.",
    adm: "Admissions to all the courses of MLR Institute of Technology are entrance-based. Admissions to the B.Tech courses are based on TS-EAMCET., while admissions to M.Tech are on GATE or TS-PGCET Entrance exam scores. Admissions to the MBA courses are based on TS-ICET scores. ",
    fee: "Bachelor of Technology [B.Tech] ₹ 110,000",
    plac: "MLRIT Placements 2023 is in progress & till now, 733 job offers have been made to the students. 658 students have been placed with unique offers. MLRIT highest package stood at INR 58 LPA. 32 MNCs have already participated in the placement drive. The highest number of selections have been made by Virtusa as it made a total of 226 placements alone with a salary range of INR INR 5.5 LPA to INR 7 LPA. Other top recruiters included DXC, Accenture, EPAM, Brillio etc.The institute conducted its summer Internship placement drive for the batch 2021 and the Highest Stipend stood at INR 60K per Month. Some of the top recruiters like Amazon, TATA, Mahindra, Wipro, TCS, Optum, Infosys, HCL, Capgemini, participated in the placement drive of 2021.",
  },
  {
    id: 13,
    name: "VNR Vignana Jyothi Institute of Engineering & Technology, Hyderabad",
    Rating: "3.9",
    Nirf: "NIRF\nRanked 135 out of 300",
    info: "Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering and Technology established in 1995, is a reputed engineering college in Hyderabad, recognized by (AICTE) and affiliated to the Jawaharlal Nehru Technological University, Hyderabad. The Institution offers courses in UG and PG Level (B. Tech and M.Tech) and is accredited by NAAC with 'A++' Grade and NBA. It is constantly ranked amongst the Top Engineering Colleges in India and was ranked 127 by NIRF in 2020. Admission to the courses is done through the merit scored in the entrance examinations.",
    adm: "Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering and Technology offers B.Tech courses across 15 streams for the duration of 4 years. It also offers M.Tech. courses across 9 streams for the duration of 2 years, accredited by NBA. The courses offered by this institute are affiliated to Jawaharlal Nehru Technological University.Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering and Technology offers B.Tech and M.Tech courses in Engineering and Technology domain. The admissions are conducted through entrance exams. There are 15 undergraduate courses with 9 postgraduate courses. ",
    fee: "Fee:Bachelor of Technology [B.Tech] ₹ 131,000",
    plac: "The students are eligible for campus placements since 2nd-year 2nd semester the companies like jp Morgan, Amazon, oracle etc for the college they may select the students like 150 members. The highest package is about 30lakhs and the average package is 6 lakhs. There are 90% of students are placed in the college every year.There are many companies that visit our college and provide placements for students with a good stipend and the companies like jp Morgan, Amazon, oracle etc will provide internships with 70k per month on average. They give real-time projects for students which helps in a real-time world.",
  },
  {
    id: 14,
    name: "Gokaraju Rangaraju Institute of Engineering",
    Rating: "4.3",
    info: "GRIET was established in 1997, under the patronage of the Gokaraju Rangaraju Educational Society, created by Dr. Gokaraju Ganga Raju, the chairman of griet.GRIET is located in a campus of eighteen acres in Bachupally village, close to the Hyderabad-Mumbai National Highway, and 4 km from Jawaharlal Nehru Technological University, Kukatpally, Hyderabad. The college is situated on a lush green hilly plot.",
    adm: "Gokaraju Rangaraju Institute of Engineering and Technology (GRIET) offers UG and PG courses in numerous specializations. It offers B. Tech and M. Tech programme. Candidate can apply to this Institute online. Admission in the courses are based on Entrance Examination. ",
    fee: "Fee:Bachelor of Technology [B.Tech] ₹ 138,500",
    plac: " In 3rd year ending internships are provided for the students and coding competitions will be there for the recruiting process. projects at our college are soil moisture detectors, smart sticks, hospital management e.t.c few companies are Amazon, darwinbox, cisco, nworx, beautiful code, and Broadridge.Many companies visit our college for placements like Amazon, Microsoft and etc. The highest package is above 900000 and average is 500000. Nearly 80-90percent students will get placed",
  },
  {
    id: 15,
    name: "Sreenidhi Institute of Science & Technology (SNIST), Hyderabad",
    Rating: "4.2",
    info: "Sreenidhi Institute of Science and Technology (SNIST), Hyderabad, is a not-for-profit university run by Sreenidhi Educational Group of the Sree Group of Industries and approved by UGC. SNIST offers undergraduate and postgraduate in Engineering and management domains. Admission into SNIST Hyderabad, is provided on the basis of merit as well as entrance test. Apart from academics, the total number of placements over the last 7 years is on a consistent average rate of 84%. The highest package offered amounts to INR 38 LPA.",
    adm: "Bachelor of Technology [B.Tech] ₹ 130,000",
    fee: "Fee:Bachelor of Technology [B.Tech] ₹ 130,000",
    plac: "Looking at the SNIST placement record, a total of 770 students were placed with the highest salary package of INR 14.5 LPA and an average salary package of 4 LPA in 2020. Some of the top recruiters are Google, Infosys, Cognizant, Tech Mahindra, Deloitte, Amazon, Wipro, HCL, IBM, Capgemini, Hyundai, Oracle, L&T, Accenture, Adobe, HSBC, etc.",
  },
  {
    id: 16,
    name: "Vardhaman College of Engineering, Hyderabad",
    Rating: "2.7",
    Nirf: "NIRF\nRanked 141 out of 300",
    info: "Vardhaman College of Engineering was established in the year 1999 in Hyderabad. It is approved by the All India Council for Technical Education (AICTE) and affiliated to Jawaharlal Nehru Technological University (JNTU), Hyderabad. It was awarded autonomous status recently and is accredited with A grade certificate by the National Assessment and Accreditation Council (NAAC). Vardhaman College of Engineering in Hyderabad is ranked in 143rd rank in NIRF 2020. ",
    adm: "Vardhaman College of Engineering is currently offering M.Tech, MBA, courses at PG level and 6 B.Techcourses as Civil Engineering, Electrical & Electronics Engineering, Mechanical Engineering, Electronics & Communication Engineering, Computer Science & Engineering, and Information Technology at UG level.Admissions are merit-based which is done based on the state-level entrance exam and GATE cut-off declared by the college each year. VCE conducts its admission process through proper counseling sessions for respective programs.",
    fee: "Fee:Bachelor of Technology [B.Tech] ₹ 140,000",
    plac: "Vardhaman College of Training has successfully placed nearly 90% in the year 2010 and with the best of placing a record of 95% students in the consecutive years of 2011 and 2012. The college has accreditation of TATA Consultancy Services which ensures that TCS which is a global level organization will visit the college every year for placing the students in it. In addition to TCS, several other famous organizations like IBM, BYJU’S, Amazon, HCL etc. also visit the college regularly for placements.",
  },
  {
    id: 17,
    name: "Institute of Aeronautical Engineering, Hyderabad",
    Rating: "4.6",
    Nirf: "NIRF\nRanked 159 out of 300",
    info: "Institute of Aeronautical Engineering (IARE), Hyderabad was established in the year 2000 and is run by Maruthi Educational Society. It is the first institute to start a B.Tech program in Aeronautical Engineering in the state of Telangana and has gradually transformed itself into an integrated multi-disciplinary technological institute. IARE is a prestigious engineering college offering eleven B.Tech programs, six M.Tech programs and MBA (Master of Business Administration) course under four specialization, with 20 years of rich standing in the educational sphere.",
    adm: "IARE, Hyderabad offers four year full time B.Tech and B.Tech (Lateral) program at the undergraduate level, and two year full time M.Tech and MBA programs at the postgraduate level.",
    fee: "Fee:B.Tech	₹1.01 Lakhs",
    plac: "IARE has been consistently improving its placement record with more than 75% of students being placed in various reputed organizations. The placement and training (PAT) cells play a pivotal role in building the career of aspiring engineers enabling them to hone their skills in order to reach their desired goals. IARE maintains good relations with corporate houses and other prestigious institutions being a perfect host for educationists and entrepreneurs. ",
  },
  {
    id: 18,
    name: " Matrusri Engineering College",
    Rating: "4.0",
    info: "Matrusri Engineering College, Hyderabad was established in 2011. It is a private college affiliated to Osmania University and welcomes nearly 600 students each year. The college offers courses in Civil Engineering, Computer Science and Engineering, Electronics and Communication Engineering, Electrical and Electronics Engineering, Information Technology and Mechanical Engineering. The UG programs in engineering have been accredited by NBA in 2019. The college follows the EAMCET counseling procedure to admit students for its courses.",
    adm: "Matrusri Engineering College was established in 2011. The college offers B.E. degrees in various fields of Engineering. Matrusri Engineering College offers 5 4-year full-time B.E. courses with a total intake of 420. The admission to B.E program is offered by Matrusri Engineering College on the basis of the Andhra Pradesh Engineering Agriculture Medical Courses Common Entrance Test ( EAMCET).",
    fee: "Fee:Bachelor of Engineering [BE] ₹ 110,000",
    plac: "Matrusri Engineering College has a separate placements cell under which it carries out various placements drives and placements training. The college provides excellent assistance when it comes to placements. The Campus Recruitment Training is conducted right from the second year. The T&P cell assists and facilitates the recruitment teams in conducting online assessment tests, group discussions, and personal interviews.The highest salary package stood at INR 32 LPA till now and for the 2023 batch, the highest salary package was INR 25 LPA. More than 80% of students get placed each year through college placement programs. ",
  },
  {
    id: 19,
    name: "Anurag University Hyderabad",
    Rating: "4.1",
    info: "Anurag University, Hyderabad runs under Gayathri Educational and Cultural Trust (GECT). The trust was founded in the year 1998 by ‘Guru’ Sri Sivananda Murthy Garu to impart quality education. The Anurag Group of Institutions (AGI) is one of the first few integrated campuses of South India established in 2002, offering programs in Engineering & Technology, Pharmacy, and Business Management. In the year 2020, AGI was officially named as Anurag University. The Institute is affiliated to JNTU, Hyderabad and approved by UGC.The institute spread over 50 acres offers quality education to 6500+ students comprising 48% of women. The institution adopts world-class teaching-learning pedagogy that is constantly appraised and revised to align with the trends in global higher education. Anurag University has 650 teaching and non-teaching fraternity.",
    adm: "dmission to the courses offered by the Institute is done in two categories – Category A and Category B. The Category A seats are filled by the Government of Telangana and accounts for 70% of the total intake. This is generally done on the basis of performance in EAMCET and PGCET for undergraduate and postgraduate courses respectively. The Category B seats are filled by the Management of the college based on academic merit.",
    fee: "Fee:B.Tech	₹2.5 Lakhs",
    plac: "The Placement Cell of Anurag Institute has tied up with numerous industry partners. More than 98% of students recruited from different institutes of the university are being placed in a different corporate position.Anurag University Placements 2022 is concluded with 2000+ offers. Anurag University average package stood at INR 4.7 LPA whereas Anurag University highest package stood at INR 38.5 LPA. More than 150 recruiters participated in the placement drive. Some of the top recruiters of Anurag University Placements 2022 are Cognizant, Accenture, Capgemini etc.",
  },
];
